# Generated by Django 3.1.1 on 2020-09-28 14:47

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200928_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(default=datetime.timedelta(days=-1, seconds=20002)),
            preserve_default=False,
        ),
    ]
